version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=sample
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data
