//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Env {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Env() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Infrastructure.Resources.Env", typeof(Env).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string ConnectionStringDefault {
            get {
                return ResourceManager.GetString("ConnectionStringDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:Authority.
        /// </summary>
        internal static string SecurityAuthority {
            get {
                return ResourceManager.GetString("SecurityAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:CallbackPath.
        /// </summary>
        internal static string SecurityCallbackPath {
            get {
                return ResourceManager.GetString("SecurityCallbackPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:ClientId.
        /// </summary>
        internal static string SecurityClientId {
            get {
                return ResourceManager.GetString("SecurityClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:ClientSecret.
        /// </summary>
        internal static string SecurityClientSecret {
            get {
                return ResourceManager.GetString("SecurityClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:ResponseType.
        /// </summary>
        internal static string SecurityResponseType {
            get {
                return ResourceManager.GetString("SecurityResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:Scopes.
        /// </summary>
        internal static string SecurityScopes {
            get {
                return ResourceManager.GetString("SecurityScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionCookieLifetimeMinutes.
        /// </summary>
        internal static string SessionCookieLifetimeMinutes {
            get {
                return ResourceManager.GetString("SessionCookieLifetimeMinutes", resourceCulture);
            }
        }
    }
}
